# -*- coding: utf-8 -*-
"""Live_tweet_analysis .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0zaHKq_s_6_L8d8YFfdcWLdYCmw1Thu
"""

import tweepy
import matplotlib.pyplot as plt
from  textblob import TextBlob 
import time

consumer_key = "DQQPENoH4yO0rRVEkUp9unFuO"
consumer_sec = "7EjEE3t79AxsIjOHT0MoOwKfOZyTSr6jiisDqXI47ZgWxZbAsA"

access_token = "1128949700416008192-QMz8AEzCOpmukb61Qh2xUjcCUkUQ6T"
access_token_sec = "ttvS8CXmnSl6haXagCWkQvyi1Mthwrt5QgPGTHsv6cU6P"

dir(tweepy)

auth=tweepy.OAuthHandler(consumer_key,consumer_sec)

auth.set_access_token(access_token,access_token_sec)
api_connect=tweepy.API(auth)
tweet_data=api_connect.search('rahul',count=1000)

pos=0
neg=0
neu=0

# printing line by line
for tweet in tweet_data:
   #print(tweet.text)
   analysis=TextBlob(tweet.text)
   print(analysis.sentiment)
   # now checking polarity only
   if analysis.sentiment.polarity > 0:
      print("posative")
      pos=pos+1
   elif analysis.sentiment.polarity == 0 :
      print("Neutral")
      neu=neu+1
   else :
      print("Negative")
      neg=neg+1
      
# ploting graphs
plt.xlabel("tags")
plt.ylabel("polarity")
#plt.bar(['pos','neg','neu'],[pos,neg,neu])
plt.pie([pos,neg,neu],labels=['GOOD GOING','CHUTIYA HAI','GAAND MARAYE(apneko kya'],autopct="%1.1f%%")
plt.show()